---
# missing 4 topics
- ros_topic_name: "/rover/front_left_steering_pos"
  gz_topic_name: "wheel/frontleft/steering/pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/front_right_steering_pos"
  gz_topic_name: "wheel/frontright/steering/pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/rear_left_steering_pos"
  gz_topic_name: "wheel/backleft/steering/pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/rear_right_steering_pos"
  gz_topic_name: "wheel/backright/steering/pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ



- ros_topic_name: "/rover/cmd_vel"
  gz_topic_name: "/model/rover/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# wheels velocity 
# - ros_topic_name: "/rover/front_left_wheel_vel_cmd"
#   gz_topic_name: "/model/rover/front_left_wheel_vel_cmd"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/rover/rear_left_wheel_vel_cmd"
#   gz_topic_name: "/model/rover/rear_left_wheel_vel_cmd"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/rover/front_right_wheel_vel_cmd"
#   gz_topic_name: "/model/rover/front_right_wheel_vel_cmd"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/rover/rear_right_wheel_vel_cmd"
#   gz_topic_name: "/model/rover/rear_right_wheel_vel_cmd"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
- ros_topic_name: "/rover/front_left_wheel_vel_cmd"
  gz_topic_name: "wheel/frontleft/traction/vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/rear_left_wheel_vel_cmd"
  gz_topic_name: "wheel/backleft/traction/vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/front_right_wheel_vel_cmd"
  gz_topic_name: "wheel/frontright/traction/vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rover/rear_right_wheel_vel_cmd"
  gz_topic_name: "wheel/backright/traction/vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ



- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/odom"
  gz_topic_name: "/model/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/rover/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/demo/model/rover/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

